"""create garden grape variety and season

Revision ID: 470916b55dd5
Revises: 
Create Date: 2026-09-26 16:53:11.799713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470916b55dd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gardens',
    sa.Column('garden_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('garden_name', sa.String(length=150), nullable=False),
    sa.Column('owner_name', sa.String(length=150), nullable=True),
    sa.Column('location_note', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('garden_id')
    )
    op.create_table('grape_varieties',
    sa.Column('variety_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variety_name', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('variety_id'),
    sa.UniqueConstraint('variety_name')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('acquisition_type', sa.Enum('OWNED', 'PURCHASED', name='season_acquisition_type'), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'HARVESTING', 'COMPLETED', name='season_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.garden_id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['grape_varieties.variety_id'], ),
    sa.PrimaryKeyConstraint('season_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    op.drop_table('grape_varieties')
    op.drop_table('gardens')
    # ### end Alembic commands ###
