"""create worker labor worker payment and expense

Revision ID: 5d114655cc90
Revises: a05ba251424e
Create Date: 2026-09-26 17:13:19.886950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d114655cc90'
down_revision: Union[str, Sequence[str], None] = 'a05ba251424e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('worker_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('worker_payments',
    sa.Column('worker_payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('worker_payment_id')
    )
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_table('labor_records',
    sa.Column('labor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('labor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labor_records')
    op.drop_table('expenses')
    op.drop_table('worker_payments')
    op.drop_table('workers')
    # ### end Alembic commands ###
